<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'backoffice_anecdote_browse' => [[], ['_controller' => 'App\\Controller\\AnecdoteController::browse'], [], [['text', '/backoffice/anecdote/']], [], []],
    'backoffice_anecdote_read' => [['id'], ['_controller' => 'App\\Controller\\AnecdoteController::read'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/backoffice/anecdote/read']], [], []],
    'backoffice_anecdote_edit' => [['id'], ['_controller' => 'App\\Controller\\AnecdoteController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/backoffice/anecdote/edit']], [], []],
    'backoffice_anecdote_add' => [[], ['_controller' => 'App\\Controller\\AnecdoteController::add'], [], [['text', '/backoffice/anecdote/add']], [], []],
    'backoffice_anecdote_delete' => [['id'], ['_controller' => 'App\\Controller\\AnecdoteController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/backoffice/anecdote/delete']], [], []],
    'api_anecdote_browse' => [[], ['_controller' => 'App\\Controller\\Api\\AnecdoteController::browse'], [], [['text', '/anecdotes']], [], []],
    'backoffice_category_browse' => [[], ['_controller' => 'App\\Controller\\CategoryController::browse'], [], [['text', '/backoffice/category/']], [], []],
    'backoffice_category_read' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::read'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/backoffice/category/read']], [], []],
    'backoffice_category_edit' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/backoffice/category/edit']], [], []],
    'backoffice_category_add' => [[], ['_controller' => 'App\\Controller\\CategoryController::add'], [], [['text', '/backoffice/category/add']], [], []],
    'backoffice_category_delete' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/backoffice/category/delete']], [], []],
    'backoffice_user_browse' => [[], ['_controller' => 'App\\Controller\\UserController::browse'], [], [['text', '/backoffice/user/']], [], []],
    'backoffice_user_read' => [['id'], ['_controller' => 'App\\Controller\\UserController::read'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/backoffice/user/read']], [], []],
    'backoffice_user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/backoffice/user/edit']], [], []],
    'backoffice_user_add' => [[], ['_controller' => 'App\\Controller\\UserController::add'], [], [['text', '/backoffice/user/add']], [], []],
    'backoffice_user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/backoffice/user/delete']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
