nelmio_cors:
    paths:
        '^/api':
            origin_regex: true
            allow_origin: ['https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$', 'http://ec2-3-89-241-97.compute-1.amazonaws.com/']
            allow_headers: ['Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
            allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE']
            expose_headers: ['Link']
            max_age: 3600
