nelmio_cors:
    paths:
        '^/':
            origin_regex: true
            allow_origin: ['https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            expose_headers: ['Link']
            max_age: 3600
