<?php

namespace ContainerDhFx72q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C9QAxtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C9QAxt_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C9QAxt_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'anecdote' => ['privates', '.errored..service_locator.C9QAxt_.App\\Entity\\Anecdote', NULL, 'Cannot autowire service ".service_locator.C9QAxt_": it references class "App\\Entity\\Anecdote" but no such service exists.'],
        ], [
            'anecdote' => 'App\\Entity\\Anecdote',
        ]);
    }
}
