<?php

namespace ContainerDhFx72q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DWxzBzzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DWxzBzz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DWxzBzz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'user' => ['privates', '.errored..service_locator.DWxzBzz.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.DWxzBzz": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'passwordHasher' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
