<?php

namespace ContainerDhFx72q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9rtmUjVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9rtmUjV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9rtmUjV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AnecdoteController::browse' => ['privates', '.service_locator.GsTx518', 'get_ServiceLocator_GsTx518Service', true],
            'App\\Controller\\AnecdoteController::delete' => ['privates', '.service_locator.bzZMkpI', 'get_ServiceLocator_BzZMkpIService', true],
            'App\\Controller\\AnecdoteController::edit' => ['privates', '.service_locator.C9QAxt_', 'get_ServiceLocator_C9QAxtService', true],
            'App\\Controller\\AnecdoteController::read' => ['privates', '.service_locator.GsTx518', 'get_ServiceLocator_GsTx518Service', true],
            'App\\Controller\\Api\\AnecdoteController::browse' => ['privates', '.service_locator.GsTx518', 'get_ServiceLocator_GsTx518Service', true],
            'App\\Controller\\CategoryController::browse' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.bmG4G8k', 'get_ServiceLocator_BmG4G8kService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\CategoryController::read' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\UserController::add' => ['privates', '.service_locator.nWpr6Po', 'get_ServiceLocator_NWpr6PoService', true],
            'App\\Controller\\UserController::browse' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.PaJQGxZ', 'get_ServiceLocator_PaJQGxZService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.DWxzBzz', 'get_ServiceLocator_DWxzBzzService', true],
            'App\\Controller\\UserController::read' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AnecdoteController:browse' => ['privates', '.service_locator.GsTx518', 'get_ServiceLocator_GsTx518Service', true],
            'App\\Controller\\AnecdoteController:delete' => ['privates', '.service_locator.bzZMkpI', 'get_ServiceLocator_BzZMkpIService', true],
            'App\\Controller\\AnecdoteController:edit' => ['privates', '.service_locator.C9QAxt_', 'get_ServiceLocator_C9QAxtService', true],
            'App\\Controller\\AnecdoteController:read' => ['privates', '.service_locator.GsTx518', 'get_ServiceLocator_GsTx518Service', true],
            'App\\Controller\\Api\\AnecdoteController:browse' => ['privates', '.service_locator.GsTx518', 'get_ServiceLocator_GsTx518Service', true],
            'App\\Controller\\CategoryController:browse' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.bmG4G8k', 'get_ServiceLocator_BmG4G8kService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\CategoryController:read' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\UserController:add' => ['privates', '.service_locator.nWpr6Po', 'get_ServiceLocator_NWpr6PoService', true],
            'App\\Controller\\UserController:browse' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.PaJQGxZ', 'get_ServiceLocator_PaJQGxZService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.DWxzBzz', 'get_ServiceLocator_DWxzBzzService', true],
            'App\\Controller\\UserController:read' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AnecdoteController::browse' => '?',
            'App\\Controller\\AnecdoteController::delete' => '?',
            'App\\Controller\\AnecdoteController::edit' => '?',
            'App\\Controller\\AnecdoteController::read' => '?',
            'App\\Controller\\Api\\AnecdoteController::browse' => '?',
            'App\\Controller\\CategoryController::browse' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::read' => '?',
            'App\\Controller\\UserController::add' => '?',
            'App\\Controller\\UserController::browse' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::read' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AnecdoteController:browse' => '?',
            'App\\Controller\\AnecdoteController:delete' => '?',
            'App\\Controller\\AnecdoteController:edit' => '?',
            'App\\Controller\\AnecdoteController:read' => '?',
            'App\\Controller\\Api\\AnecdoteController:browse' => '?',
            'App\\Controller\\CategoryController:browse' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:read' => '?',
            'App\\Controller\\UserController:add' => '?',
            'App\\Controller\\UserController:browse' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:read' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
