<?php

namespace ContainerDhFx72q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BzZMkpIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bzZMkpI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bzZMkpI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'anecdote' => ['privates', '.errored..service_locator.bzZMkpI.App\\Entity\\Anecdote', NULL, 'Cannot autowire service ".service_locator.bzZMkpI": it references class "App\\Entity\\Anecdote" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'anecdote' => 'App\\Entity\\Anecdote',
            'entityManager' => '?',
        ]);
    }
}
