<?php

namespace ContainerDhFx72q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnecdoteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.C9QAxt_.App\Entity\Anecdote' shared service.
     *
     * @return \App\Entity\Anecdote
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.C9QAxt_": it references class "App\\Entity\\Anecdote" but no such service exists.');
    }
}
